- name: Coping Redis Repo  
  ansible.builtin.copy:                    # Copies the file from the files directory
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: Installing Redis 
  ansible.builtin.package:
    name: redis-6.2.7
    state: present  

- name: Updating MongoDB Config
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Restarting service 
  ansible.builtin.service:
    name: redis
    state: restarted
    enabled: true  

- name: Set-Hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}} 