- name: Coping Redis Repo  
  ansible.builtin.copy:                    # Copies the file from the files directory
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: Installing Nginx
  ansible.builtin.package:
    name: nginx
    state: present 