filebeat.inputs:
- type: log
  enabled: true
  json.keys_under_root: true

  paths:
    - "{{LOGLOCATION}}"

  fields:
   component: "{{COMPONENT}}"
   logtype: "{{LOGTYPE}}"

# ============================== Filebeat modules ==============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false


# ======================= Elasticsearch template setting =======================

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:

  # Kibana Host
  # Scheme and port can be left out and will be set to the default (http and 5601)

  #space.id:
# ------------------------------ Logstash Output -------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["172.31.67.103:5044"]

# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
