- name: Installing Maven 
  ansible.builtin.yum:
    name: 
       - maven 
    state: present 

- name: Creating Roboshop User
  include_role:
    name: common
    tasks_from: create-user

- name: Download and extracting the Component 
  include_role:
    name: common
    tasks_from: download 

- name: Uninstall password validate plugin 
  ansible.builtin.shell: echo "uninstall plugin validate_password;" | mysql -uroot -p"{{DB_PASSWORD}}"
  ignore_errors: yes 