- name: Demo on using variables   
  hosts: all
  vars:                                    # Delcaring variables at play level; All tasks of the play can access this variable URL 
    URL: play.google.com 
  vars_files:
    - demo-vars.yaml 
    
  tasks: 
    - name: Printing URL 
      ansible.builtin.debug:
        msg: "{{URL}}"

    - name: Printing URLs 
      ansible.builtin.debug:
        msg: value of URL is {{URL}} 
      vars:                               # Declaring the variable at task level ( Local variable )
        URL: task.google.com 

    - name: Printing CLI_URL 
      ansible.builtin.debug:
        msg: value of CLI_URL is {{CLI_URL}}

# How do your print a variable in bash ????  ${varName}
# To print a vairable in yaml, we will {{varName}}

# Varaible name has to be enclosed in quotes only if it's the only entity in the msg, if not you don't have to place them in quotes. 
# Always prefer to keep the task name different ; In version, it used to throw error. In version 7, that's deprecated.

# Ansible throws you an error if you use a variable that is not declared  ; In bash, it assume it as a empty variable.


# CLI Variables > Local Varaible  >  Global Variable 