- name: Demo on Shell Module    
  hosts: all 
  tasks: 
    - name: Execute Shell Command 
      ansible.builtin.shell: uptime
      register: OUT                          # Register captures the output of the shell command and preserves it in the variable with name of our choice.

    - name: Prinint OUT Variable 
      ansible.builtin.debug:
        msg: "{{OUT}}"