- name: Demo on Ignore Errors
  hosts: all 
  tasks: 
    - name: Checking where Tomcat is running or not 
      ansible.builtin.shell: ps -ef | grep tomcat | grep -v grep 
      register: OUT      
      ignore_errors: yes     

    - name: Starting Tomcat 
      ansible.builtin.debug: 
        msg: Starting Tomcat  