- name: Demo on using Conditions   
  hosts: all
  vars:                                    
    actions: true
  tasks: 
    - name: Run this on Centos Machines Only  
      ansible.builtin.debug:
        msg: Hai I am CentOS
      when: ansible_distribution == "CentOS" 

    - name: Run this on Ubuntu Machines Only  
      ansible.builtin.debug:
        msg: Hai I am Ubuntu 
      when: ansible_distribution == "Ubuntu" 
    
    - name: Run this action  
      ansible.builtin.debug:
        msg: I will only run when Actions is true 
      when: actions