- name: Coping filebeat repo 
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo 

- name: Installing Filebeat 
  ansible.builtin.yum:
      name: filebeat
      state: present

- name: Start filebeat 
  ansible.builtin.systemd:
    state: restarted
    name: filebeat
    daemon_reload: yes
    enabled: true 
