- name: Configuring the ublic signing key
  ansible.builtin.shell: sudo rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch

- name: Coping filebeat repo 
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo 

- name: Installing Filebeat 
  ansible.builtin.yum:
      name: filebeat
      state: present

- name: Coping filebeat configuration 
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: Start filebeat 
  ansible.builtin.systemd:
    state: restarted
    name: filebeat
    daemon_reload: yes
    enabled: true 
