- name: Coping Logstash Config
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Restarting Logstash 
  ansible.builtin.systemd:
    state: restarted
    name: logstash
    daemon_reload: yes
    enabled: true 

- name: Wait for logstash port to come in listening stage
  ansible.builtin.wait_for:
    port: 5044
    delay: 40
    timeout: 75
