- name: Coping MySql Repo  
  ansible.builtin.copy:                    # Copies the file from the files directory
    src: "{{COMPONENT}}.repo"
    dest: /etc/yum.repos.d/{{COMPONENT}}.repo 

- name: Installing MySql 
  ansible.builtin.yum:
    name: 
       - mysql-community-server
       - MySQL-python
    state: present  

- name: Starting MySQL service 
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: true  

- name: Reading MySQL Log File 
  ansible.builtin.slurp:
      src: /var/log/mysqld.log 
  register: mysql_log 

- name: Connecting using default password  
  block:
    - name: Grep mysql version
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{DB_PASSWORD}}" 
        filter: version
  
  rescue: 
    - name: Reading MySQL Log File 
      ansible.builtin.slurp:
         src: /var/log/mysqld.log 
      register: mysql_log  

    - name: Copy root password change command 
      ansible.builtin.copy:
        src: root-pass.sql 
        dest: /tmp/root-pass.sql 

    - name: Changing the default password 
      ansible.builtin.shell: mysql --connect-expired-password -uroot -p"{{mysql_log['content'] | b64decode | regex_findall('temporary password.*')| join(' ') | split(' ')| last}}"   <   /tmp/root-pass.sql

- name: Uninstall password validate plugin 
  ansible.builtin.shell: echo "uninstall plugin validate_password;" | mysql -uroot -p"{{DB_PASSWORD}}"
  ignore_errors:



    # - name: Printing 
    #   ansible.builtin.debug:
    #     msg: "{{DEFAULT_PASS}}"

