- name: Coping MySql Repo  
  ansible.builtin.copy:                    # Copies the file from the files directory
    src: {{COMPONENT}}.repo
    dest: /etc/yum.repos.d/{{COMPONENT}}.repo 

- name: Installing MySql 
  ansible.builtin.yum:
    name: mongodb-org
    state: present  