- name: Coping MySql Repo  
  ansible.builtin.copy:                    # Copies the file from the files directory
    src: "{{COMPONENT}}.repo"
    dest: /etc/yum.repos.d/{{COMPONENT}}.repo 

- name: Installing MySql 
  ansible.builtin.yum:
    name: 
       - mysql-community-server
       - MySQL-python
    state: present  

- name: Starting MySQL service 
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: true  

- name: Reading MySQL Log File 
  ansible.builtin.slurp:
      src: /var/log/mysqld.log 
  register: mysql_log 

- name: Connecting using default password  
  block:
    - name: Grep mysql version
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{DB_PASSWORD}}" 
        filter: version
  
  rescue: 
    - name: Reading MySQL Log File 
      ansible.builtin.slurp:
         src: /var/log/mysqld.log 
      register: mysql_log  

    - name: Coping Password File  
      ansible.builtin.copy:                    # Copies the file from the files directory
        src: "root-pass.sql"
        dest: /tmp/root-pass.sql

    - name: Change Default Password
      ansible.builtin.shell: mysql --connect-expired-password -uroot -p"{{ mysql_log['content'] | b64decode | regex_findall('temporary password.*') |  join(' ') | split(' ') | last }}"  </tmp/root-pass.sql 

    - name: Check Validate plugin exists
      ansible.builtin.shell: echo "uninstall plugin validate_password;" | mysql -uroot -p{{DB_PASSWORD}}
      ignore_errors: yes
