- name: Coping MySql Repo  
  ansible.builtin.copy:                    # Copies the file from the files directory
    src: "{{COMPONENT}}.repo"
    dest: /etc/yum.repos.d/{{COMPONENT}}.repo 

- name: Installing MySql 
  ansible.builtin.yum:
    name: 
       - mysql-community-server
       - MySQL-python
    state: present  

- name: Starting MySQL service 
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: true  

- name: Collect all info except settings and users by root
  community.mysql.mysql_info:
    login_user: root
    login_password: RoboShop@1
  ignore_errors: yes  

- name: Reset Password 
  debug: