- name: Coping Prometheus Config
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Restarting Prometheus 
  ansible.builtin.systemd:
    state: restarted
    name: prometheus
    daemon_reload: yes
    enabled: true 

- name: Wait for logstash port to come in listening stage
  ansible.builtin.wait_for:
    port: 9090
    delay: 10
    timeout: 30
