- name: Creating the Application User Account 
  ansible.builtin.user:
    name: "{{APPUSER}}"
    comment: roboshop service account 
  register: APPUSER_INFO

- name: Installing boto3 and botocore
  ansible.builtin.pip:
    name:
      - botocore
      - boto3 
    executable: pip3