- name: Install Maven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: Creating Roboshop User
  include_role:
    name: common
    tasks_from: create-user

- name: Download and extracting the Component 
  include_role:
    name: common
    tasks_from: download-nexus 

- name: Preparing Maven Artifact 
  ansible.builtin.shell: mvn clean package && mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar
  args:
    chdir: /home/{{APPUSER}}/{{COMPONENT}}/
  become_user: "{{APPUSER}}" 

- name: Configuring Service
  include_role:
    name: common
    tasks_from: config-svc

- name: Set-Hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}} 