- name: Configuring NodejS Repo
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash - 

- name: Installing NodeJS 
  ansible.builtin.package:
    name: nodejs 
    state: present 

- name: Creating Roboshop User
  include_role:
    name: common
    tasks_from: create-user

- name: Download pem file
  ansible.builtin.get_url:
    url: https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
    dest: /home/roboshop/
    mode: '0440'
    owner: roboshop 
    group: roboshop

- name: Download and extracting the Component 
  include_role:
    name: common
    tasks_from: download-nexus

# Uncomment it only when you directly download it from the nexus.
# - name: Install node.js packages
#   community.general.npm:
#     path: /home/{{APPUSER}}/{{COMPONENT}}/

- name: Configuring Service
  include_role:
    name: common
    tasks_from: config-svc

- name: Configuring rsyslog
  include_role:
    name: elk
    tasks_from: rsyslog

- name: Installing filebeat
  include_role:
    name: elk
    tasks_from: filebeat

- name: Installing node_exporter
  include_role:
    name: prometheus
    tasks_from: node-exporter

- name: Set-Hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}} 
